### ISSUE TITLE
사용자 정보에 따른 졸업 요건 판단

### ISSUE THREAD

**Issue by JeukHwang** [sparcs-kaist/otlplus#946]
# Summary 

사용자 정보를 기반으로 졸업 필요 학점과 수강 필요 과목을 계산합니다

# Tasks 

- [x] 전공 트랙 정의
- [x] 사용자 정보로 각 학부별 졸업 필요 학점 얻어오기
- [ ] 사용자 정보로 각 학부별 수강 필요 과목 알아보기
- [ ]  학사 시스템의 전공을 가져와서 연결
- [ ] 특기자전형 별도 처리

# More info
사용자 정보: 전공 트랙(졸업 학과+복부심융전), 학번, 입학 연도
졸업 요건: 학점, 과목
